# -*- coding: utf-8 -*-
"""churndataset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efTQFK0DqhFKAt73Yd_LGqJR5zDXpqIn
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

a=pd.read_csv("/content/Churn_Modelling.csv")
a

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
a['Surname']=le.fit_transform(a['Surname'])
a['Geography']=le.fit_transform(a['Geography'])
a['Gender']=le.fit_transform(a['Gender'])
a

print(a.dtypes)

x=a.iloc[:,:13]
x

y=a['Exited'].values
y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=20)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

model=RandomForestClassifier()
model.fit(x_train,y_train)

predict=model.predict(x_test)
predict

print(accuracy_score(y_test,predict))

